version: '3'
networks:
  tp1_net:
    external:
      name: tp1_net
services:
  client_app_1:
    container_name: client_app_1
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=1
    networks:
      - tp1_net

  client_app_2:
    container_name: client_app_2
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=2
    networks:
      - tp1_net
 
  client_app_3:
    container_name: client_app_3
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=3
    networks:
      - tp1_net

  client_app_4:
    container_name: client_app_4
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=4
    networks:
      - tp1_net
 
  client_app_5:
    container_name: client_app_5
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=5
    networks:
      - tp1_net

  client_app_6:
    container_name: client_app_6
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=6
    networks:
      - tp1_net

  client_app_7:
    container_name: client_app_7
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=7
    networks:
      - tp1_net
 
  client_app_8:
    container_name: client_app_8
    image: client_app:latest
    entrypoint: /client_app
    volumes:
      - type: bind 
        source: ./client_app/config.yaml
        target: /config.yaml
    environment:
      - ID=8
    networks:
      - tp1_net