address:
  ip: "server"
  port: "12345"
client:
  timeout: 5s
log:
  level: 'debug'
workers:
  database:
    writers: 4
    readers: 4
    mergers: 4
  connection: 1
queues:
  database:
    readers: 64
    writers: 256
    merger-admin: 256
    mergers: 256
  alarm-manager: 64
  connection: 64
  dispatcher: 256
database:
  epoch-duration: 2s
  files-path: ./files
alarm:
  period: 60s
  config-path: ./alarms.json